title: Alexander Lippold
url: https://alexander-lippold.github.io
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-include-cache


title: Alexander Lippold
url: https://alexander-lippold.github.io

# Load the Minimal Mistakes theme remotely (no extra files needed)
remote_theme: "mmistakes/minimal-mistakes@4.27.3"
plugins:
  - jekyll-include-cache

minimal_mistakes_skin: default   # or "air", "contrast", etc.

include:
  - _pages

# Left sidebar author box
author:
  name: Alexander Lippold
  avatar: "/images/headshot.png"     # path to the image you added
  bio: "TODO"
  location: "City, Country"
  email: "you@domain.tld"
  links:
    - label: CV
      icon: "fas fa-file-alt"
      url: "/files/cv.pdf"
    - label: GitHub
      icon: "fab fa-github"
      url: "https://github.com/YOUR_USERNAME"
    - label: Google Scholar
      icon: "ai ai-google-scholar"
      url: "https://scholar.google.com/"

# (Optional) navigation across the top
# nav:
#   - title: "CV"
#     url: /files/cv.pdf
